### ISSUE TITLE
Add a feature to search for all available commands

### ISSUE THREAD

**Issue by vitalyford** [AdamSpera/mykelos#1]
Great work! Could you add a search field of some sort so that we would be able to find all available commands for a specific Cisco device?

**Comment by AdamSpera** [comment]
Improvements to come when HP and Aruba support is added, until then, the fill options will be a tad ugly.

![Image](https://user-images.githubusercontent.com/64236429/193956024-1aaf8e41-b3a5-49ef-a0f8-7547925dc7ac.png)

**Comment by vitalyford** [comment]
Nicely done!
